// <auto-generated />
using System;
using LojiteksWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojiteksWeb.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojiteksWeb.Models.TblBaslik", b =>
                {
                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("aciklama");

                    b.Property<long>("Bkno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("bkno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Bkno"));

                    b.Property<long?>("CihazId")
                        .HasColumnType("bigint")
                        .HasColumnName("CihazID");

                    b.Property<long?>("Firma")
                        .HasColumnType("bigint")
                        .HasColumnName("firma");

                    b.Property<int?>("GonderiAdedi")
                        .HasColumnType("int")
                        .HasColumnName("gonderiAdedi");

                    b.Property<DateOnly?>("GonderimTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("gonderimTarihi")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("kayitTarihi")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Kullanici")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("kullanici");

                    b.Property<long?>("Musteri")
                        .HasColumnType("bigint")
                        .HasColumnName("musteri")
                        .HasComment("tblMustrei-mkno ile bağlı");

                    b.Property<string>("Po")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("po");

                    b.Property<string>("Sevkiyat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sevkiyat");

                    b.Property<bool?>("Silindi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi");

                    b.Property<int?>("Tipi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("tipi")
                        .HasComment("0 - sevkiyat");

                    b.ToTable("tblBaslik", null, t =>
                        {
                            t.HasTrigger("trg_tblBaslik_Delete");

                            t.HasTrigger("trg_tblBaslik_Insert");

                            t.HasTrigger("trg_tblBaslik_Update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("LojiteksWeb.Models.TblBildirim", b =>
                {
                    b.Property<long>("Bikno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("bikno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Bikno"));

                    b.Property<string>("Bildirim")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("bildirim");

                    b.Property<byte?>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("durum");

                    b.Property<string>("Kullanici")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("kullanici");

                    b.Property<DateTime?>("Tarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("tarih")
                        .HasDefaultValueSql("(getdate())");

                    b.ToTable("tblBildirim", (string)null);
                });

            modelBuilder.Entity("LojiteksWeb.Models.TblCihaz", b =>
                {
                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("apiKey");

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("apiUrl");

                    b.Property<long>("Ckno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ckno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Ckno"));

                    b.Property<long?>("Firma")
                        .HasColumnType("bigint")
                        .HasColumnName("firma")
                        .HasComment("tblfirma-fkno ile bağlı");

                    b.Property<string>("Kod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("kod");

                    b.Property<string>("SeriNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("seriNo");

                    b.Property<string>("Tanim")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tanim");

                    b.Property<int?>("Tipi")
                        .HasColumnType("int")
                        .HasColumnName("tipi")
                        .HasComment("0 sbox");

                    b.Property<int?>("Uygulama")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("uygulama")
                        .HasComment("0 lojiteks ");

                    b.ToTable("tblCihaz", (string)null);
                });

            modelBuilder.Entity("LojiteksWeb.Models.TblEpc", b =>
                {
                    b.Property<long?>("BaslikNo")
                        .HasColumnType("bigint")
                        .HasColumnName("baslikNo");

                    b.Property<string>("Beden")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("beden");

                    b.Property<long>("EKno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("eKno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EKno"));

                    b.Property<string>("Epc")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("Firma")
                        .HasColumnType("bigint")
                        .HasColumnName("firma");

                    b.Property<DateTime?>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("kayitTarihi")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("KoliNo")
                        .HasColumnType("bigint")
                        .HasColumnName("koliNo");

                    b.Property<bool?>("Silindi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi");

                    b.Property<string>("Upc")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("upc");

                    b.ToTable("tblEpc", (string)null);
                });

            modelBuilder.Entity("LojiteksWeb.Models.TblFirma", b =>
                {
                    b.Property<long>("Fkno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fkno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Fkno"));

                    b.Property<string>("Unvan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unvan");

                    b.ToTable("tblFirma", (string)null);
                });

            modelBuilder.Entity("LojiteksWeb.Models.TblKoli", b =>
                {
                    b.Property<int?>("Adet")
                        .HasColumnType("int")
                        .HasColumnName("adet");

                    b.Property<long?>("BaslikNo")
                        .HasColumnType("bigint")
                        .HasColumnName("baslikNo");

                    b.Property<long?>("Firma")
                        .HasColumnType("bigint")
                        .HasColumnName("firma");

                    b.Property<string>("KoliBarkodu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("koliBarkodu");

                    b.Property<long?>("KoliId")
                        .HasColumnType("bigint")
                        .HasColumnName("koliId");

                    b.Property<long>("SKno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sKno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SKno"));

                    b.Property<bool?>("Silindi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("silindi");

                    b.Property<DateTime?>("Tarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("tarih")
                        .HasDefaultValueSql("(getdate())");

                    b.ToTable("tblKoli", (string)null);
                });

            modelBuilder.Entity("LojiteksWeb.Models.TblKullanici", b =>
                {
                    b.Property<string>("AdSoyad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adSoyad");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<long?>("Firma")
                        .HasColumnType("bigint")
                        .HasColumnName("firma");

                    b.Property<long>("KKno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("kKno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KKno"));

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("kullaniciAdi");

                    b.Property<string>("Sifre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sifre");

                    b.Property<string>("TwoFactorCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("TwoFactorCodeExpiration")
                        .HasColumnType("datetime");

                    b.Property<short?>("TwoFactorCounter")
                        .HasColumnType("smallint");

                    b.Property<int?>("Yetki")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("yetki");

                    b.ToTable("tblKullanici", (string)null);
                });

            modelBuilder.Entity("LojiteksWeb.Models.TblLisan", b =>
                {
                    b.Property<long>("LKno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("lKno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LKno"));

                    b.Property<DateTime?>("BaslangicTarih")
                        .HasColumnType("datetime")
                        .HasColumnName("baslangicTarih");

                    b.Property<DateTime?>("BitisTarih")
                        .HasColumnType("datetime")
                        .HasColumnName("bitisTarih");

                    b.Property<long>("Cihaz")
                        .HasColumnType("bigint")
                        .HasColumnName("cihaz")
                        .HasComment("tblCihaz.ckno ile eslestir");

                    b.Property<long>("Firma")
                        .HasColumnType("bigint")
                        .HasColumnName("firma")
                        .HasComment("tblFirma.fkno ile eslestir");

                    b.Property<DateTime>("KayitTarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("kayitTarih")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LisansTip")
                        .HasColumnType("int")
                        .HasColumnName("lisansTip")
                        .HasComment("0: tarih aralikli lisans, 1: suresiz lisans");

                    b.HasKey("LKno");

                    b.ToTable("tblLisans", (string)null);
                });

            modelBuilder.Entity("LojiteksWeb.Models.TblMusteri", b =>
                {
                    b.Property<long?>("Firma")
                        .HasColumnType("bigint")
                        .HasColumnName("firma");

                    b.Property<long>("Mkno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("mkno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Mkno"));

                    b.Property<string>("Musteri")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("musteri");

                    b.ToTable("tblMusteri", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
